name: cbtify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  auto_size_text: ^3.0.0
  confetti: ^0.7.0
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  gradient_borders: ^1.0.0
  intl: ^0.19.0
  lottie: ^3.1.0
  overlay_support: ^2.1.0
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  provider: ^6.1.2
  sensors_plus: ^5.0.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.3
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/animations/